### ISSUE TITLE
Non-mpi build fails with GCC-5

### ISSUE THREAD

**Issue by qingshanchen** [NVIDIA/AMGX#9] opened 2018-01-24 17:23 UTC
Hi,
I tried to build AMGX on ubuntu 16.04, but was not able to go very far.
Basic information about my system:
Ubuntu 16.04,
gcc, g++, 5.4.0
cuda 7.5

Compilation fails at 4%:
[  4%] Building NVCC (Device) object base/CMakeFiles/amgx_base.dir/src/energymin/interpolators/amgx_base_generated_em_interpolator.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

Any suggestions on how to move forward? Thanks a lot!

**Comment by marsaev** [comment] 2018-01-25 15:22
Hi there,

CUDA 7.5 is considered to be outdated, please use newer versions, preferable >= 9.0.

Thanks,

**Comment by qingshanchen** [comment] 2018-01-25 20:52
Thanks for the response! 
So I installed CUDA 9.1 on my system. CMAKE complained about not having the default settings for CUDA (>=9.0), and so I copied over the default settings for CUDA 9.0 for CUDA 9.1. The build was then able to proceed. It was able to complete about 60% of the whole process, and failed at 'Linking C executable amgx_capi'. Here are the error messages:

### 
[ 61%] Linking CXX executable eigensolver
[ 61%] Built target amgxsh
Scanning dependencies of target amgx_capi
[ 61%] Building C object examples/CMakeFiles/amgx_capi.dir/amgx_capi.c.o
[ 61%] Linking C executable amgx_capi
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)4, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)4, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)1, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)1, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)0, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)4, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)4, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)3, (AMGX_MatPrecision)3, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)3, (AMGX_MatPrecision)3, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)3, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)3, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)3, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)3, (AMGX_MatPrecision)4, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)0, (AMGX_VecPrecision)1, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)1, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
../libamgxsh.so: undefined reference to `amgx::aggregation::Aggregation_AMG_Level_Base<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)3, (AMGX_MatPrecision)3, (AMGX_IndPrecision)2> >::Aggregation_AMG_Level_Base(amgx::AMG<(AMGX_VecPrecision)3, (AMGX_MatPrecision)3, (AMGX_IndPrecision)2>*, amgx::ThreadManager*)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/amgx_capi.dir/build.make:100: recipe for target 'examples/amgx_capi' failed
make[2]: *** [examples/amgx_capi] Error 1
CMakeFiles/Makefile2:429: recipe for target 'examples/CMakeFiles/amgx_capi.dir/all' failed
make[1]: *** [examples/CMakeFiles/amgx_capi.dir/all] Error 2
###

Please advise. Thanks!

**Comment by marsaev** [comment] 2018-02-01 00:27
Hi @qingshanchen ,

Can you upload full build log with error somewhere?

Thanks,

**Comment by qingshanchen** [comment] 2018-02-01 03:37
@marsaev Thank you for your response! The build log with errors is attached. I could not find any official log for the build. The attached file essentially is a copy-paste of the screen outputs. 

For what is worth, I got the same errors on a CentOS 7.0 with CUDA 8.0 and gcc 5.4.0. 
[amgx-build-log.txt](https://github.com/NVIDIA/AMGX/files/1684092/amgx-build-log.txt)

Thanks!

**Comment by qingshanchen** [comment] 2018-02-06 22:09
It turns out that this is problem associated with the no_mpi flag. Once I remove this flag, the build was able to proceed to completion. I was able to build AMGX on both Ubuntu 16.04 with CUDA 9.1 and Centos 7.0 with CUDA 8.0.

**Comment by qingshanchen** [comment] 2018-02-06 22:09
Title changed to reflect the nature of the problem.

**Comment by shwina** [comment] 2018-02-08 01:05
I get the same error with a similar log on Ubuntu 16.05, CUDA 9.0, GCC 5.4.0. Building with MPI works, but without MPI fails to build the target `examples/amgx_capi` .

**Comment by marsaev** [comment] 2018-02-08 13:13
I can reproduce building error with gcc 5.4.0, but it builds just fine with 4.8.4, sounds like compiler issue. Mentioned unresolved method is defined just fine : https://github.com/NVIDIA/AMGX/blob/9471b45f88e8209b670d721a839e10abaa32728d/core/src/aggregation/aggregation_amg_level.cu#L240
I'm going to look at the https://gcc.gnu.org/gcc-5/porting_to.html , but i'm open to any ideas why it happens.

**Comment by marsaev** [comment] 2018-06-19 21:17
I will actually leave it open, since I still need to look into GCC-5 build

**Comment by marsaev** [comment] 2020-07-28 11:21
Closing since we are building with later versions of gcc now

**Closed by marsaev** 2020-07-28 11:21 UTC
Labels: build issues
