### ISSUE TITLE
Build error with windows and cuda v10.2.89, not found nvtx

### ISSUE THREAD

**Issue by rainbell** [NVIDIA/AMGX#87] opened 2020-03-17 02:31 UTC
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files: 
nvtx

**Comment by marsaev** [comment] 2020-03-18 16:18
Hey @rainbell ,

Can you provide your OS, cmake version, compiler version and whether are you running latest commit on master?

Thanks,

**Comment by rainbell** [comment] 2020-03-19 02:29
> Hey @rainbell ,
> 
> Can you provide your OS, cmake version, compiler version and whether are you running latest commit on master?
> 
> Thanks,

@marsaev Sure, thanks. 
I am using the latest master branch code and the building environment is 
 "vs2017 (_MSVC_VER=1916) + cuda v10.2 + cmake v3.12(&v3.16)" on Windows 10 system. 
(I also tried vs2015+cuda v9.2+cmake v3.16 on Win10. The same.)
Although cmake checking could pass by removing all nvtx related things, the compiling process still 
 reports many "identifier xxx is undefined" errors.

**Comment by mattmartineau** [comment] 2020-03-20 10:33
Hi @rainbell,

Would you mind checking if the pull request https://github.com/NVIDIA/AMGX/pull/88 fixes your issue?

Thanks
Matt

**Comment by fizmat** [comment] 2020-03-21 11:07
I have the same problem. Visual Studio 15 2017 Win64, CUDA 10.2

I somehow managed to force cmake to find the library, but then it can't find the headers. Technically nvtx exists on Windows (C:\Program Files\NVIDIA Corporation\NvToolsExt). Is it really necessary to disable it, or is it possible to hint to cmake where to find it?

Maybe at some point AMGX can move to CUDA as a language and FindCUDAToolkit? I don't know enough about cmake and AMGX to say how hard that would be.

**Comment by rainbell** [comment] 2020-03-22 02:31
@mattmartineau Thanks for the fix #88 , it does solve most of my problem ! 
However, another error says that the symbol "cusparseSetMatFullPrecision" couldn't be parsed occurs while I tried to build amgxsh. 
Is this because I'm using cuda v10.2? I found the annotation in base/include/amgx_cusparse.h said "The internal function cusparseSetMatFullPrecision is no longer exposed since CUDA 10.1.", which seems to be related with my problem.
Thanks again.

**Comment by mattmartineau** [comment] 2020-03-23 08:57
That's right - we can no longer rely on cusparseSetMatFullPrecision, which is now internal. For the moment the only way we can resolve the problem is to disable mixed precision for CUDA 10.2 onwards including the calls to cusparseSetMatFullPrecision. It requires another small code change so I will update the pull request and ping here at some point soon.

**Comment by mattmartineau** [comment] 2020-03-24 12:04
I update the pull request so that we use DISABLE_MIXED_PRECISION instead of CUSPARSE_GENERIC_INTERFACES to guard all of the mixed precision elements. This separates the enabling of the cuSPARSE generic interfaces, which aren't yet available on Windows, and the mixed precision loss in CUDA 10.1+. I tested this on Windows 10 VS 2017 and CUDA 10.2. It built for me, let me know if it fixes the issues for you.

**Comment by rainbell** [comment] 2020-03-25 08:33
@mattmartineau It built for me too! Thanks a lot!

**Comment by marsaev** [comment] 2020-03-25 09:02
Great, thanks for the help, Matthew!
#88 is merged to master.

**Closed by marsaev** 2020-03-25 09:02 UTC
Labels: build issues

**Comment by marsaev** [comment] 2020-03-25 09:30
> Maybe at some point AMGX can move to CUDA as a language and FindCUDAToolkit? I don't know enough about cmake and AMGX to say how hard that would be.

@fizmat , yes, we definitely will move to CUDA language at some point. It become more and more robust with each CMake release and we use it for other projects.
