### ISSUE TITLE
[Question] Does it support devices of compute capability 70?

### ISSUE THREAD

**Issue by hkqdtc1** [NVIDIA/AMGX#23] opened 2018-03-16 13:30 UTC
I have a Titan V card and I've successfully compiled the codes. But when I was trying to run the example I got the following errors. does 'invalid device function' mean that it currently does not support Titan V? Thanks.
```
➜  build git:(master) examples/amgx_capi -m ../examples/matrix.mtx -c ../core/configs/FGMRES_AGGREGATION.json
AMGX version 2.0.0.130-opensource
Built on Mar 16 2018, 21:21:21
Compiled with CUDA Runtime 9.1, using CUDA driver 9.1
Warning: No mode specified, using dDDI by default.
Thrust failure: parallel_for failed: invalid device function
File and line number are not available for this exception.
Caught amgx exception: Cuda failure: 'invalid device function'
```

**Comment by BeneBr** [comment] 2018-03-19 02:44
You have the latest version drivers of your card?

**Comment by hkqdtc1** [comment] 2018-03-19 02:56
yes:

```
Device 0: "Graphics Device"
  CUDA Driver Version / Runtime Version          9.1 / 9.1
  CUDA Capability Major/Minor version number:    7.0
  Total amount of global memory:                 12055 MBytes (12640911360 bytes)
  (80) Multiprocessors, ( 64) CUDA Cores/MP:     5120 CUDA Cores
  GPU Max Clock rate:                            1455 MHz (1.46 GHz)
  Memory Clock rate:                             850 Mhz
  Memory Bus Width:                              3072-bit
  L2 Cache Size:                                 4718592 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 7 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 65 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.1, CUDA Runtime Version = 9.1, NumDevs = 1
Result = PASS
➜  deviceQuery nvidia-smi 
Mon Mar 19 10:55:37 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 00000000:41:00.0  On |                  N/A |
| 28%   34C    P8    24W / 250W |    288MiB / 12055MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1339      G   /usr/lib/xorg/Xorg                           161MiB |
|    0      2212      G   compiz                                       126MiB |
+-----------------------------------------------------------------------------+

```

**Comment by marsaev** [comment] 2018-03-19 03:13
Hey @hkqdtc1 ,

Yes, it does. Make sure you run your cmake with -DCUDA_ARCH="70".
Also, try running example with environment variable:
> CUDA_LAUNCH_BLOCKING=1

This will allow to get more precise diagnostics.

**Comment by hkqdtc1** [comment] 2018-03-19 04:05
Thanks @marsaev 

I reran the followings steps:
# cmake
```
➜  build git:(master) cmake ../  -DCUDA_ARCH="70" -DCMAKE_NO_MPI=1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
Non-MPI build has been forced
This is a MPI build:false
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.1 (found version "9.1") 
Cuda libraries: /usr/local/cuda-9.1/lib64/libcudart_static.a-lpthreaddl/usr/lib/x86_64-linux-gnu/librt.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kahu/AMGX/build
```
# run make
```
make -j16 all
...[ 79%] Building NVCC (Device) object tests/CMakeFiles/amgx_tests_library.dir/src/amgx_tests_library_generated_test_utils.cu.o
Scanning dependencies of target amgx_tests_library
[ 79%] Linking CXX static library libamgx_tests_library.a
[ 79%] Built target amgx_tests_library
[ 80%] Building NVCC (Device) object tests/CMakeFiles/amgx_tests_launcher.dir/src/amgx_tests_launcher_generated_utest.cu.o
Scanning dependencies of target amgx_tests_launcher
[ 80%] Linking CXX executable amgx_tests_launcher
[100%] Built target amgx_tests_launcher
```
# run example
```
➜  build git:(master) export CUDA_LAUNCH_BLOCKING=1                                                                     
➜  build git:(master) echo $CUDA_LAUNCH_BLOCKING=1 
1=1
➜  build git:(master) examples/amgx_capi -m ../examples/matrix.mtx -c ../core/configs/FGMRES_AGGREGATION.json           
AMGX version 2.0.0.130-opensource
Built on Mar 19 2018, 11:55:38
Compiled with CUDA Runtime 9.1, using CUDA driver 9.1
Warning: No mode specified, using dDDI by default.
Thrust failure: parallel_for failed: invalid device function
File and line number are not available for this exception.
Caught amgx exception: Cuda failure: 'invalid device function'
 at: /home/kahu/AMGX/core/src/solvers/dense_lu_solver.cu:698
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : void amgx::dense_lu_solver::DenseLUSolver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)1, (AMGX_MatPrecision)1, (AMGX_IndPrecision)2> >::allocMem<int, unsigned long>(int*&, unsigned long, bool)+0x4d4
 /home/kahu/AMGX/build/libamgxsh.so : amgx::dense_lu_solver::DenseLUSolver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::DenseLUSolver(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0xf2
 /home/kahu/AMGX/build/libamgxsh.so : amgx::dense_lu_solver::DenseLUSolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::create(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x31
 /home/kahu/AMGX/build/libamgxsh.so : amgx::SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::allocate(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x10b
 /home/kahu/AMGX/build/libamgxsh.so : amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2>::AMG(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x7d7
 /home/kahu/AMGX/build/libamgxsh.so : amgx::AlgebraicMultigrid_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::AlgebraicMultigrid_Solver(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x3c
 /home/kahu/AMGX/build/libamgxsh.so : amgx::AlgebraicMultigrid_SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::create(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x31
 /home/kahu/AMGX/build/libamgxsh.so : amgx::SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::allocate(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x10b
 /home/kahu/AMGX/build/libamgxsh.so : amgx::FGMRES_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::FGMRES_Solver(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x666
 /home/kahu/AMGX/build/libamgxsh.so : amgx::FGMRES_SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::create(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x25
 /home/kahu/AMGX/build/libamgxsh.so : amgx::SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::allocate(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x10b
 /home/kahu/AMGX/build/libamgxsh.so : amgx::AMG_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::init()+0x19c
 /home/kahu/AMGX/build/libamgxsh.so : amgx::AMG_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::AMG_Solver(amgx::Resources*, amgx::AMG_Configuration*)+0x4a
 /home/kahu/AMGX/build/libamgxsh.so : amgx::CWrapHandle<AMGX_solver_handle_struct*, amgx::AMG_Solver<amgx::TemplateMode<(AMGX_Mode)8193>::Type> >* amgx::(anonymous namespace)::create_managed_mode_object<(AMGX_Mode)8193, amgx::AMG_Solver, AMGX_solver_handle_struct*, amgx::Resources*, amgx::AMG_Configuration*>(AMGX_solver_handle_struct**, AMGX_Mode, amgx::Resources*, amgx::AMG_Configuration*)+0x46
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_solver_create()+0x29a
 examples/amgx_capi : main()+0x1ed
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_matrix_handle_struct*>(AMGX_matrix_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromMatrixHandle(AMGX_matrix_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_matrix_get_size_impl()+0x3c
 examples/amgx_capi : main()+0x239
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_solver_handle_struct*>(AMGX_solver_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromSolverHandle(AMGX_solver_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_solver_setup()+0x36
 examples/amgx_capi : main()+0x34c
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_solver_handle_struct*>(AMGX_solver_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromSolverHandle(AMGX_solver_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_solver_solve()+0x39
 examples/amgx_capi : main()+0x360
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_solver_handle_struct*>(AMGX_solver_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromSolverHandle(AMGX_solver_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_solver_get_status()+0x3f
 examples/amgx_capi : main()+0x36f
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_solver_handle_struct*>(AMGX_solver_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromSolverHandle(AMGX_solver_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_solver_destroy()+0x33
 examples/amgx_capi : main()+0x379
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29

Caught amgx exception: Mode not found.

 at: /home/kahu/AMGX/base/include/amgx_c_wrappers.inl:646
Stack trace:
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_Mode amgx::(anonymous namespace)::get_mode_from<AMGX_matrix_handle_struct*>(AMGX_matrix_handle_struct* const&)+0x112
 /home/kahu/AMGX/build/libamgxsh.so : amgx::getResourcesFromMatrixHandle(AMGX_matrix_handle_struct*, amgx::Resources**)+0x36
 /home/kahu/AMGX/build/libamgxsh.so : AMGX_matrix_destroy_impl()+0x33
 examples/amgx_capi : main()+0x397
 /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
 examples/amgx_capi : _start()+0x29
```
To be noted that I have a Threadripper 1950x CPU with 16 cores. Not sure if it could be problematic.

**Comment by marsaev** [comment] 2018-03-20 12:38
Hmmm, interesting. Looks like issue happens in thrust. Unfortunately diagnostics with thrust are little bit tricky.
Can you also update drivers to r390? (www.nvidia.com/drivers) - I think it's required for 9.1.
Are you able to successfully run some other CUDA samples? Can you also try to run some example from thrust code? (https://github.com/thrust/thrust/tree/master/examples). 
Before the releasing the code i tested single-GPU aggregation and classical path on few examples with V100 and it did work just fine, maybe it's Titan-V specifics? I will be able to test it on Titan-V in the beginning of next month.
There would be also CUDA toolkit update to 9.2 (which includes thrust) early next month (after GTC), so some of the issues might be fixed there.

**Comment by marsaev** [comment] 2018-03-20 12:38
CPU should not be the issue.

**Comment by hkqdtc1** [comment] 2018-03-20 12:44
Thanks @marsaev. I am currently running Ubuntu 16.04 and the latest driver is 387.34
```
Version: | 387.34
-- | --
Release Date: | 2017.12.8
Operating System: | Linux 64-bit Ubuntu 16.04
CUDA Toolkit: | 9.0
Language: | English (US)
File Size: | 78.48 MB
```
But I do notice that for Ubuntu 17.04 there is version 390.3. I am going to update my OS and see what happens.

**Comment by marsaev** [comment] 2018-03-20 12:50
Do you mean that available in the ppa repository? 
By the link above you can download r390 package for 16.04 (click "Show all operating systems")

**Comment by hkqdtc1** [comment] 2018-03-20 13:11
Hmmm I did exactly the same but for TITAN V, there is no option for selecting CUDA version(while for Tesla I do see the option to configure cuda 9.0 or 9.1) and with the config I got the result of 387.34.
![image](https://user-images.githubusercontent.com/12600718/37656215-63788b28-2c82-11e8-9380-a12cde2b6d42.png)
![image](https://user-images.githubusercontent.com/12600718/37656440-002ad214-2c83-11e8-80c7-d445bf9deedc.png)

![image](https://user-images.githubusercontent.com/12600718/37656323-ace31828-2c82-11e8-9c5f-f1e116cf78b5.png)
But there is 390.3 for Tesla V under Ubuntu 16.04, as well as 390.3 for Titan V under Ubuntu 17.04:
![image](https://user-images.githubusercontent.com/12600718/37656383-dbbda30c-2c82-11e8-9d20-f6f947be862b.png)
![image](https://user-images.githubusercontent.com/12600718/37656461-0d3bed8a-2c83-11e8-93f7-fc672fe76c02.png)

**Or does it mean the Tesla V driver and Titan V drive are inter-changeable?**

**Comment by marsaev** [comment] 2018-03-20 15:27
It should be the case. Just to be sure you can download driver package, extract it (unpack *.deb with 'dpkg-deb' or extract files from *.run by running it with '-x- option) and see list of supported devices in the 'Appendix A' of the README.txt

**Comment by marsaev** [comment] 2018-03-20 15:32
Oh i see. Actually if you choose generic 'Linux x64' in the driver's operating system selector it will suggest you r390 as well. If you want to stick to deb packages - use Tesla driver. V100 and TitanV use same GV100 chip, so drivers should support both.

**Comment by hkqdtc1** [comment] 2018-03-24 12:09
Updating to driver 390 still wouldn't work. I am going to try ubuntu 17.04.

**Comment by marsaev** [comment] 2018-03-24 12:43
@hkqdtc1 can you try some to compile/run simple CUDA/thrust example?

**Comment by hkqdtc1** [comment] 2018-03-27 05:42
I've tried the thrust examples and they look running fine:

## segmentationTreeThrust
```
➜  segmentationTreeThrust sudo ./segmentationTreeThrust
./segmentationTreeThrust Starting...

GPU Device 0: "TITAN V" with compute capability 7.0

* Building segmentation tree... done in 72.6255 (ms)
* Dumping levels for each tree...

➜  segmentationTreeThrust ls
```

## radixSortThrust
```
➜  radixSortThrust ls
doc       NsightEclipse.xml  radixSortThrust.cu  readme.txt
Makefile  radixSortThrust    radixSortThrust.o
➜  radixSortThrust ./radixSortThrust 
./radixSortThrust Starting...

GPU Device 0: "TITAN V" with compute capability 7.0


Sorting 1048576 32-bit unsigned int keys and values

radixSortThrust, Throughput = 993.1582 MElements/s, Time = 0.00106 s, Size = 1048576 elements
Test passed

```

**Comment by marsaev** [comment] 2018-03-29 02:09
It looks like GPU, driver, compiler and thrust are fine since tests do pass, so it's something with AMGX/CUDA libraries.
I'll try to reproduce issue on TitanV. Meanwhile i think CUDA 9.2 will be released soon and it would be worth trying compile with latest release.

**Comment by hkqdtc1** [comment] 2018-03-29 04:19
@marsaev I've updated the OS to Ubuntu 17.10 with the latest driver released on 3.28.2018 and it seems to work :)

**Comment by BeneBr** [comment] 2018-03-29 11:11
Good.

**Comment by meujin** [comment] 2018-04-05 06:58
I have a same problem on Amazon p3.2xlarge instance with tesla v100. OS is Ubuntu 16.04, cuda 9.1. I tried to use different versions of drivers: 390.30 (from official ubuntu repository), 390.46 (last driver for ubuntu 16.04 on nvidia.com), 390.48 (last driver for titan linux x64) anyway error.

deviceQuery:

> Detected 1 CUDA Capable device(s)
> 
> Device 0: "Tesla V100-SXM2-16GB"
>   CUDA Driver Version / Runtime Version          9.1 / 9.1
>   CUDA Capability Major/Minor version number:    7.0
>   Total amount of global memory:                 16160 MBytes (16945512448 bytes)
>   (80) Multiprocessors, ( 64) CUDA Cores/MP:     5120 CUDA Cores
>   GPU Max Clock rate:                            1530 MHz (1.53 GHz)
>   Memory Clock rate:                             877 Mhz
>   Memory Bus Width:                              4096-bit
>   L2 Cache Size:                                 6291456 bytes
>   Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
>   Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
>   Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
>   Total amount of constant memory:               65536 bytes
>   Total amount of shared memory per block:       49152 bytes
>   Total number of registers available per block: 65536
>   Warp size:                                     32
>   Maximum number of threads per multiprocessor:  2048
>   Maximum number of threads per block:           1024
>   Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
>   Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
>   Maximum memory pitch:                          2147483647 bytes
>   Texture alignment:                             512 bytes
>   Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
>   Run time limit on kernels:                     No
>   Integrated GPU sharing Host Memory:            No
>   Support host page-locked memory mapping:       Yes
>   Alignment requirement for Surfaces:            Yes
>   Device has ECC support:                        Enabled
>   Device supports Unified Addressing (UVA):      Yes
>   Supports Cooperative Kernel Launch:            Yes
>   Supports MultiDevice Co-op Kernel Launch:      Yes
>   Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 30
>   Compute Mode:
>      < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> 
> deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.1, CUDA Runtime Version = 9.1, NumDevs = 1
> Result = PASS

**Comment by marsaev** [comment] 2018-04-05 12:37
So you have error similar to one in the initial comment to this issue?

**Comment by meujin** [comment] 2018-04-05 12:40
Here is my error:
> terminate called after throwing an instance of 'amgx::amgx_exception'
>   what():  Cuda failure: 'invalid device function'
> 
> Caught signal 6 - SIGABRT (abort)
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::handle_signals(int)+0xd6
>  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x11390
>  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0x38
>  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a
>  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : __gnu_cxx::__verbose_terminate_handler()+0x16d
>  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x8d6b6
>  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x8c6a9
>  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : __gxx_personality_v0()+0x2e5
>  /lib/x86_64-linux-gnu/libgcc_s.so.1 : ()+0xff83
>  /lib/x86_64-linux-gnu/libgcc_s.so.1 : _Unwind_RaiseException()+0xfb
>  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : __cxa_throw()+0x5c
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::dense_lu_solver::DenseLUSolver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::~DenseLUSolver()+0x26f
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::dense_lu_solver::DenseLUSolver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::~DenseLUSolver()+0x9
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::AMG<(AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2>::~AMG()+0x38
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::AlgebraicMultigrid_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::AlgebraicMultigrid_Solver(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x67
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::AlgebraicMultigrid_SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::create(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x31
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::SolverFactory<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::allocate(amgx::AMG_Config&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, amgx::ThreadManager*)+0x10b
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::AMG_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::init()+0x19c
>  /home/ubuntu/AMGX/libamgxsh.so : amgx::AMG_Solver<amgx::TemplateConfig<(AMGX_MemorySpace)1, (AMGX_VecPrecision)0, (AMGX_MatPrecision)0, (AMGX_IndPrecision)2> >::AMG_Solver(amgx::Resources*, amgx::AMG_Configuration*)+0x4a
>  /home/ubuntu/AMGX/libamgxsh.so : AMGX_solver_create()+0x190
>  ./solver_amg.exe() [0x409b29]
>  ./solver_amg.exe() [0x4139bb]
>  ./solver_amg.exe() [0x407f85]
>  ./solver_amg.exe() [0x407e8a]
>  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf0
>  ./solver_amg.exe() [0x407269]
> Aborted (core dumped)
> 
I think it is similar to the initial comment

**Comment by marsaev** [comment] 2018-04-05 12:47
RIght, looks similar.

Could you also run your example with environment variable CUDA_LAUNCH_BLOCKING=1 ?

**Comment by meujin** [comment] 2018-04-05 12:53
I tried no changes.

**Comment by marsaev** [comment] 2018-04-08 11:54
Is same configuration (GPU, input, configuration, binaries) do work locally for you? If so - i would try to reproduce your local environment on the remote machine as much as possible - use same CUDA distribution, drivers as on the machine with successful runs. In this issue someone had success with changing SW setup. Have you tried, by the chance, running on some other amazon instance with different GPU? 
Are you running same binaries or rebuild AMGX and test binary on the target machine? I would suggest doing the latter.

**Comment by meujin** [comment] 2018-04-30 11:05
Change OS to RedHat 7 and using driver from cuda toolkit 9.1 solved the problem.

**Closed** 2018-06-19 21:14 UTC
